version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - eno-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - eno-network

  functions:
    build: ./functions
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./functions:/app
      - /app/node_modules
    networks:
      - eno-network

networks:
  eno-network:
    driver: bridge 