apiVersion: v1
kind: Namespace
metadata:
  name: eno-health-helper
  labels:
    name: eno-health-helper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eno-backend
  namespace: eno-health-helper
  labels:
    app: eno-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eno-backend
  template:
    metadata:
      labels:
        app: eno-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/YOUR_USERNAME/eno-health-helper/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eno-frontend
  namespace: eno-health-helper
  labels:
    app: eno-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eno-frontend
  template:
    metadata:
      labels:
        app: eno-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/YOUR_USERNAME/eno-health-helper/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "http://eno-backend-service:8000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eno-functions
  namespace: eno-health-helper
  labels:
    app: eno-functions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eno-functions
  template:
    metadata:
      labels:
        app: eno-functions
    spec:
      containers:
      - name: functions
        image: ghcr.io/YOUR_USERNAME/eno-health-helper/functions:latest
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5001"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: eno-backend-service
  namespace: eno-health-helper
spec:
  selector:
    app: eno-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: eno-frontend-service
  namespace: eno-health-helper
spec:
  selector:
    app: eno-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: eno-functions-service
  namespace: eno-health-helper
spec:
  selector:
    app: eno-functions
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eno-backend-hpa
  namespace: eno-health-helper
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eno-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eno-frontend-hpa
  namespace: eno-health-helper
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eno-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
